# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bdf13815ff6c7e797809f03b52b272717eb6182d1a4e4727c7356be6e9c54d0ba00e80fb480e1dd94c20293e8dd2d6a4a9e552a022a9e131f025cbacc3fb464

test:
  secret_key_base: 35961ee27482368305cfd1ccbfdbc2c3dffdc26359820cba6fc1209a7e1c2da1e6ae58d4a432ab6766b2a5cfda38a9935d1d3a83e3738b78323bddb0ae592a94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
